# Generated by Django 5.1.2 on 2024-10-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
