# Generated by Django 5.0.6 on 2024-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
