# Generated by Django 5.0.6 on 2024-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
